source 'https://github.com/CocoaPods/Specs.git'

workspace 'holo.xcworkspace'

target 'holo' do
  platform :ios, '13.0'
  project 'holo/holo.xcodeproj'
  use_frameworks! :linkage => :static
  # VonageMLTransformers 3.1.0-dev.346 installs WebRTC 99.10.0-dev.356
  pod 'VonageMLTransformers', '= 3.1.0-dev.346'
  pod 'OTXCFramework', '= 2.27.0'
end

target 'holosim' do
  platform :ios, '13.0'
  project 'holo/holo.xcodeproj'
  use_frameworks! :linkage => :static
  # VonageMLTransformers 3.1.0-dev.346 installs WebRTC 99.10.0-dev.356
  pod 'VonageMLTransformers', '= 3.1.0-dev.346'
  pod 'OTXCFramework', '= 2.27.0'
end
