# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VonageUnityIntegration' do
  # Comment the next line if you don't want to use dynamic frameworks

    platform :ios, '12.0'
    project 'VonageUnityIntegration.xcodeproj'
    use_frameworks! :linkage => :static
    pod 'VonageWebRTC', '= 99.4.0-alpha.114'


end
